/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameUuidRouteImport } from './routes/game/$uuid'
import { Route as GameResultsUuidRouteImport } from './routes/game/results.$uuid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameUuidRoute = GameUuidRouteImport.update({
  id: '/game/$uuid',
  path: '/game/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const GameResultsUuidRoute = GameResultsUuidRouteImport.update({
  id: '/game/results/$uuid',
  path: '/game/results/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$uuid': typeof GameUuidRoute
  '/game/results/$uuid': typeof GameResultsUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$uuid': typeof GameUuidRoute
  '/game/results/$uuid': typeof GameResultsUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$uuid': typeof GameUuidRoute
  '/game/results/$uuid': typeof GameResultsUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$uuid' | '/game/results/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$uuid' | '/game/results/$uuid'
  id: '__root__' | '/' | '/game/$uuid' | '/game/results/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameUuidRoute: typeof GameUuidRoute
  GameResultsUuidRoute: typeof GameResultsUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$uuid': {
      id: '/game/$uuid'
      path: '/game/$uuid'
      fullPath: '/game/$uuid'
      preLoaderRoute: typeof GameUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/results/$uuid': {
      id: '/game/results/$uuid'
      path: '/game/results/$uuid'
      fullPath: '/game/results/$uuid'
      preLoaderRoute: typeof GameResultsUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameUuidRoute: GameUuidRoute,
  GameResultsUuidRoute: GameResultsUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
