/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as GameUuidRouteImport } from './routes/game/$uuid'
import { Route as GameResultsUuidRouteImport } from './routes/game/results.$uuid'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const GameUuidRoute = GameUuidRouteImport.update({
  id: '/game/$uuid',
  path: '/game/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const GameResultsUuidRoute = GameResultsUuidRouteImport.update({
  id: '/game/results/$uuid',
  path: '/game/results/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/game/$uuid': typeof GameUuidRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/map': typeof MapIndexRoute
  '/game/results/$uuid': typeof GameResultsUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/game/$uuid': typeof GameUuidRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/map': typeof MapIndexRoute
  '/game/results/$uuid': typeof GameResultsUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/game/$uuid': typeof GameUuidRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/map/': typeof MapIndexRoute
  '/game/results/$uuid': typeof GameResultsUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/game/$uuid'
    | '/profile/$username'
    | '/map'
    | '/game/results/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/game/$uuid'
    | '/profile/$username'
    | '/map'
    | '/game/results/$uuid'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/game/$uuid'
    | '/profile/$username'
    | '/map/'
    | '/game/results/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  GameUuidRoute: typeof GameUuidRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  MapIndexRoute: typeof MapIndexRoute
  GameResultsUuidRoute: typeof GameResultsUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$uuid': {
      id: '/game/$uuid'
      path: '/game/$uuid'
      fullPath: '/game/$uuid'
      preLoaderRoute: typeof GameUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/results/$uuid': {
      id: '/game/results/$uuid'
      path: '/game/results/$uuid'
      fullPath: '/game/results/$uuid'
      preLoaderRoute: typeof GameResultsUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  GameUuidRoute: GameUuidRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  MapIndexRoute: MapIndexRoute,
  GameResultsUuidRoute: GameResultsUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
